import { snapPoint } from "@/components/MainSection";

export const snapPoints: snapPoint[] = [1];

export const TRANSLATIONS = {
  en: {
    language: "Language",
    edit_courses: "Edit Courses",
    remove_course: "Remove Course",
    search_placeholder: "Search by name or course number...",
    no_courses: "No courses selected",
    clear_selection: "Clear Selection",
    no_grade_data: "No grade data available",
    course: "Course",
    lecturer: "Lecturer",
    semester: "Semester",
    taught_in_semesters: "Taught in semesters",
    lecturers: "Lecturers",
    group: "Group",
    groups: "Groups",
    no_group: "None",
    all_groups: "All Groups",
    moed: "Date",
    no_moed: "None",
    decisive_moed: "Decisive ex.",
    grade_range: "Grade range",
    moeds: "Dates",
    mean: "Mean",
    dates_filter: "Exams",
    clear_filters: "Clear exams",
    no_info: "No info",
    unknown: "Unknown",
    A: "A",
    B: "B",
    C: "C",
    selected_courses_will_appear_here: "Selected courses will appear here...",
    loading_data: "Loading data...",
    no_results: "No results found",
    chart_placeholder:
      "Select a course from above to see its grade distribution...",
    select_courses: "Add courses from the list...",
    faculty: "Faculty",
    download_extension: "Download Chrome Extension",
    dark_mode: "Dark Mode",
    light_mode: "Light Mode",
    save_selection: "Save Selection",
    search_exam: "Search by semester or lecturer...",
    show_in_stacked: "Show stacked",
    show_in_grouped: "Show grouped",
    no_semesters_match: "No semesters match the search",
    top_lecturers: "Top Lecturers by Average Grade",
    show_all: "Show All",
    show_less: "Show Less",
  },
  he: {
    language: "שפה",
    edit_courses: "עריכת קורסים",
    remove_course: "הסרת קורס",
    search_placeholder: "חפשו שם או מספר קורס...",
    no_courses: "לא נבחרו קורסים",
    clear_selection: "נקה בחירה",
    no_grade_data: "אין נתוני ציונים זמינים",
    course: "קורס",
    lecturer: "מרצה",
    semester: "סמסטר",
    taught_in_semesters: "לימד/ה בסמסטרים",
    lecturers: "מרצים",
    group: "קבוצה",
    groups: "קבוצות",
    no_group: "אף קבוצה",
    all_groups: "כל הקבוצות",
    moed: "מועד",
    decisive_moed: "מועד קובע",
    grade_range: "טווח ציונים",
    no_moed: "אף מועד",
    moeds: "מועדים",
    mean: "ממוצע",
    dates_filter: "סינון מועדים",
    clear_filters: "נקה מועדים",
    no_info: "אין מידע",
    unknown: "לא ידוע",
    A: "א",
    B: "ב",
    C: "ג",
    selected_courses_will_appear_here: "קורסים נבחרים יופיעו כאן...",
    loading_data: "טוען נתונים...",
    no_results: "לא נמצאו תוצאות",
    chart_placeholder: "סמנו קורס מלמעלה כדי לראות את התפלגות הציונים שלו...",
    select_courses: "הוסיפו קורסים מהרשימה...",
    faculty: "פקולטה",
    download_extension: "הורדת תוסף לכרום",
    dark_mode: "מצב לילה",
    light_mode: "מצב יום",
    save_selection: "שמור בחירה",
    search_exam: "חפשו סמסטר או שם מרצה...",
    show_in_stacked: "הצג בערימה",
    show_in_grouped: "הצג בקבוצות",
    no_semesters_match: "אין סמסטרים התואמים לחיפוש",
    top_lecturers: "מרצים מובילים לפי ציון ממוצע",
    show_all: "הצג הכל",
    show_less: "הצג פחות",
  },
  ar: {
    language: "اللغة",
    edit_courses: "تعديل الدورات",
    remove_course: "إزالة الدورة",
    search_placeholder: "ابحث بالاسم أو رقم الدورة...",
    no_courses: "لم يتم اختيار أي دورات",
    clear_selection: "مسح الاختيارات",
    no_grade_data: "لا توجد بيانات درجات متاحة",
    course: "دورة",
    lecturer: "محاضر",
    semester: "فصل دراسي",
    taught_in_semesters: "تدريس في الفصول الدراسية",
    lecturers: "محاضرون",
    group: "مجموعة",
    groups: "مجموعات",
    no_group: "لا يوجد",
    all_groups: "كل المجموعات",
    moed: "موعد",
    no_moed: "لا يوجد",
    decisive_moed: "حاسم",
    grade_range: "نطاق الدرجات",
    moeds: "مواعيد",
    mean: "المتوسط",
    dates_filter: "امتحانات",
    clear_filters: "مسح التصفية",
    no_info: "لا توجد معلومات",
    unknown: "غير معروف",
    A: "أ",
    B: "ب",
    C: "ج",
    selected_courses_will_appear_here: "الدورات المختارة ستظهر هنا...",
    loading_data: "جاري تحميل البيانات...",
    no_results: "لم يتم العثور على نتائج",
    chart_placeholder: "اختر دورة من الأعلى لرؤية توزيع درجاتها...",
    select_courses: "أضف دورات من القائمة...",
    faculty: "كلية",
    download_extension: "تحميل امتداد كروم",
    dark_mode: "الوضع الليلي",
    light_mode: "الوضع النهاري",
    save_selection: "حفظ الاختيار",
    search_exam: "ابحث بالفصل الدراسي أو اسم المحاضر...",
    show_in_stacked: "عرض مكدس",
    show_in_grouped: "عرض مجمع",
    no_semesters_match: "لا توجد فصول دراسية تطابق البحث",
    top_lecturers: "أفضل المحاضرين حسب الدرجة المتوسطة",
    show_all: "عرض الكل",
    show_less: "عرض أقل",
  },
};
